name: CI

on:
  push:
    branches:
      - master

env:
  TAG: 1.0.${{ github.run_number }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create tag
        run: |
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}

      - name: Create CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ env.TAG }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.changelog.outputs.changes }}
          tag: ${{ env.TAG }}
          makeLatest: true
          token: ${{ secrets.WORKFLOW_PAT }}
