name: ci

on:
  push:
    branches:
      - "master"

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create tag
        run: |
          git tag "1.0.${{ github.run_number }}"
          git push origin --tags
