name: ci

on:
  push:
    branches:
      - "master"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Semver release
        uses: cocogitto/cocogitto-action@v3
        id: release
        with:
          release: true

      - name: Push changes
        run:
          - "git commit --amend -m \"$(git log --format=%B -n1)\" -m \" [skip ci]\""
          - "git push"
          - "git push origin '${{ steps.release.outputs.version }}'"

      - name: Print version
        run: "echo '${{ steps.release.outputs.version }}'"
